# Generated by Django 5.2.1 on 2025-05-18 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(max_length=20, verbose_name="WhatsApp Numarası"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp İletişim",
                "verbose_name_plural": "WhatsApp İletişimleri",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "Ödeme Bildirimi"),
                            ("EXPENSE", "Gider Bildirimi"),
                            ("REMINDER", "Borç Hatırlatma"),
                        ],
                        max_length=10,
                        verbose_name="Mesaj Tipi",
                    ),
                ),
                ("content", models.TextField(verbose_name="Mesaj İçeriği")),
                (
                    "media_url",
                    models.URLField(blank=True, null=True, verbose_name="Medya URL"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("SENT", "Gönderildi"),
                            ("FAILED", "Başarısız"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="whatsapp_messaging.whatsappcontact",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Mesajı",
                "verbose_name_plural": "WhatsApp Mesajları",
                "ordering": ["-created_at"],
            },
        ),
    ]
