# Generated by Django 5.2.1 on 2025-05-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yonetim", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="yonetici_tel",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Yönetici Telefon / Manager Phone",
            ),
        ),
    ]
