# Generated by Django 5.2.1 on 2025-05-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "yonetim",
            "0003_site_aidat_miktari_alter_aidat_daire_alter_blok_site_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aidat",
            name="makbuz",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="aidat_makbuzlari/",
                verbose_name="Makbuz / Receipt",
            ),
        ),
        migrations.AddField(
            model_name="gider",
            name="makbuz",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="gider_makbuzlari/",
                verbose_name="Makbuz / Receipt",
            ),
        ),
        migrations.AlterField(
            model_name="aidat",
            name="tutar",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Tutar / Amount"
            ),
        ),
    ]
