# Generated by Django 5.2.1 on 2025-05-09 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yonetim", "0004_aidat_makbuz_gider_makbuz_alter_aidat_tutar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aidat",
            options={"ordering": ["-tarih", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="blok",
            options={"ordering": ["ad"]},
        ),
        migrations.AlterModelOptions(
            name="gider",
            options={"ordering": ["-tarih", "-id"]},
        ),
        migrations.RemoveField(
            model_name="blok",
            name="daire_sayisi",
        ),
        migrations.RemoveField(
            model_name="daire",
            name="no",
        ),
        migrations.AddField(
            model_name="daire",
            name="daire_no",
            field=models.CharField(
                default="", max_length=10, verbose_name="Daire No / Flat Number"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="daire",
            name="telefon_no",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Telefon No / Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="daire",
            name="kullanici",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daireler",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sakin / Resident",
            ),
        ),
    ]
